spring:
  application:
    name: item-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest 
#server:
#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,,http://eureka1:2002/eureka

  
---
spring:
   profiles: item1
server:
   port: 8001 

---
spring:
   profiles: item2
server:
   port: 8002