spring:
  application:
    name: order-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest  
#server:
#  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream   
---
spring:
   profiles: order1
server:
   port: 8201 

---
spring:
   profiles: order2
server:
   port: 8202
      